In [5]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns, warnings as warn
warn.filterwarnings('ignore')
%matplotlib inline
from sklearn.datasets import make_classification
from sklearn.neighbors import  KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, RandomizedSearchCV

In [10]:
X,y = make_classification(n_samples = 1000, n_classes = 2, n_features =3, n_redundant  =1, random_state = 42)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42, test_size = 0.25)

In [24]:
knn_classifier = KNeighborsClassifier(n_neighbors = 7, algorithm = 'kd_tree')

In [25]:
knn_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='kd_tree', n_neighbors=7)

In [26]:
y_pred = knn_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.924
0.9140625
0.936
[[114   8]
 [ 11 117]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92       122
           1       0.94      0.91      0.92       128

    accuracy                           0.92       250
   macro avg       0.92      0.92      0.92       250
weighted avg       0.92      0.92      0.92       250



In [27]:
params = {'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'], 'n_neighbors' : [i for i in range(1,10)]}

In [20]:
random_search_cv = RandomizedSearchCV(knn_regressor,param_distributions= params,  scoring = 'accuracy') 

In [21]:
random_search_cv.fit(X_train,y_train)

RandomizedSearchCV(estimator=KNeighborsClassifier(n_neighbors=6),
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8,
                                                        9]},
                   scoring='accuracy')

In [22]:
random_search_cv.best_score_

0.9146666666666666

In [23]:
random_search_cv.best_params_

{'n_neighbors': 7, 'algorithm': 'kd_tree'}

## K Nearest Neighbour Classifier

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=1000, # 1000 observations 
    n_features=3, # 3 total features
     n_redundant=1,
    n_classes=2, # binary target/label 
    random_state=999 
)

In [3]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
classifier=KNeighborsClassifier(n_neighbors=5,algorithm='auto')
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [16]:
y_pred=classifier.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [18]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[158  20]
 [ 11 141]]
0.906060606060606
              precision    recall  f1-score   support

           0       0.93      0.89      0.91       178
           1       0.88      0.93      0.90       152

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [ ]:
## Task 
GridsearchCV
for i k=1,2,3,4,5,6,7,8,9,10

## K best 