## Logistic Regression Implementation

In [1]:
from sklearn.datasets import load_iris

/home/user/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
dataset=load_iris()

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [4]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [7]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
df['target']=dataset.target

In [9]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [10]:
df['target'].unique()

array([0, 1, 2])

In [11]:
df[df['target']!=2]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
95,5.7,3.0,4.2,1.2,1
96,5.7,2.9,4.2,1.3,1
97,6.2,2.9,4.3,1.3,1
98,5.1,2.5,3.0,1.1,1


In [12]:
df_copy=df[df['target']!=2]

In [13]:
df_copy['target'].unique()

array([0, 1])

In [14]:
## Independent and dependent features
X=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
classification=LogisticRegression(max_iter=200)

In [18]:
classification

LogisticRegression(max_iter=200)

In [19]:
classification.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [20]:
y_pred=classification.predict(X_test)

In [21]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion Metrics,Accuracy,Classification Report

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [23]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [24]:
print(accuracy_score(y_test,y_pred))

1.0


In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Cross Validation

In [26]:
from sklearn.model_selection import KFold

In [27]:
cv=KFold(n_splits=5)

In [28]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
## these are the scores all the cross validation
scores=cross_val_score(classification,X_train,y_train,scoring='accuracy',cv=cv)

In [31]:
np.mean(scores)

1.0

In [155]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples = 5000, n_features = 20, n_informative = 10, n_redundant = 10, n_classes = 2, random_state = 42)

In [163]:
df = pd.concat([pd.DataFrame(X,columns = [f"feature_{i}" for i in range(1,21)]) , 
                pd.DataFrame(y,columns = ['target'])],axis = 1)

In [164]:
df.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,target
0,-1.578673,-1.378998,0.989135,5.823883,0.410339,-1.124754,-3.436621,-1.321341,1.701782,-1.523744,...,-6.864033,-2.680529,-2.923329,0.477600,5.260170,0.571042,0.871795,-1.346805,-2.044859,1
1,-2.514297,0.263944,-0.681486,-2.262762,-4.358898,-3.173828,-2.424513,2.766116,-0.837611,1.801214,...,1.420846,-0.815964,3.388721,0.012753,-2.753600,1.502959,1.428888,1.812405,-0.030353,0
2,-1.522428,-0.824580,1.163671,0.535840,0.770262,-0.301988,-3.917507,2.072610,0.883743,-1.161948,...,-1.560531,-1.543039,-0.867554,-0.572969,0.920906,-1.898928,-0.303063,0.482538,-4.330265,1
3,-6.349069,-2.131203,-0.958889,-1.530700,3.612492,2.375586,-2.605185,0.544563,-4.025061,-1.230866,...,-6.087054,-3.525353,-4.941087,3.630396,2.672684,-1.492063,-4.454877,1.580692,-6.820943,0
4,-0.747783,1.399029,-0.534940,2.675545,4.561243,2.290146,-0.079795,-3.253695,-0.082443,-3.017447,...,-2.853897,-3.325694,-1.514696,1.358955,-0.100363,-2.738453,-0.517626,-3.660937,-1.166361,0


In [166]:
X = df.drop('target', axis = 1)
y = df.target

In [169]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30)
logistic_regressor = LogisticRegression()
logistic_regressor.fit(X_train,y_train)
y_pred = logistic_regressor.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))

0.8333333333333334
              precision    recall  f1-score   support

           0       0.82      0.85      0.84       751
           1       0.84      0.82      0.83       749

    accuracy                           0.83      1500
   macro avg       0.83      0.83      0.83      1500
weighted avg       0.83      0.83      0.83      1500

0.8441379310344828
0.8170894526034713


In [170]:
from sklearn.model_selection import cross_val_score, KFold

In [172]:
cross_val_score(logistic_regressor, X_train, y_train, scoring = 'accuracy', cv = KFold(n_splits=5)).mean()

0.8465714285714286

In [145]:
## Lets see more complex data

# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [146]:
from sklearn.model_selection import train_test_split

In [147]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [148]:
complex_class_model=LogisticRegression(max_iter=200)

In [149]:
complex_class_model.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [150]:
y_pred_complex=complex_class_model.predict(X_test)

In [151]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [152]:
## Cross Validatiuon
cv=KFold(n_splits=5)
cross_val_score(complex_class_model,X_train,y_train,cv=cv)

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [153]:
from sklearn.datasets import load_iris
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns, warnings as warn
warn.filterwarnings('ignore')
%matplotlib inline 

In [55]:
data = load_iris()

In [71]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [57]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [90]:
df = pd.DataFrame(data.data, columns = data.feature_names)

In [92]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [93]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [94]:
df.shape

(150, 4)

In [95]:
from sklearn.linear_model import LogisticRegression

In [97]:
logistic_regressor = LogisticRegression()

In [98]:
from  sklearn.model_selection import train_test_split

In [99]:
X = df.copy()
y = data.target

In [121]:
type(X)

pandas.core.frame.DataFrame

In [122]:
type(y)

numpy.ndarray

In [128]:
df = pd.concat([X,pd.DataFrame(y,columns = ['target'])],axis=1)

In [132]:
df = df[df.target!=2]

In [133]:
X = df.drop(['target'], axis = 1)
y = df['target']

In [134]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.30)

In [135]:
logistic_regressor.fit(X_train,y_train)

LogisticRegression()

In [136]:
y_pred = logistic_regressor.predict(X_test)

In [137]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [138]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, recall_score, precision_score

In [139]:
accuracy_score(y_test,y_pred)

1.0

In [140]:
print(confusion_matrix(y_test,y_pred))

[[14  0]
 [ 0 16]]


In [141]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        16

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [143]:
precision_score(y_test,y_pred)

1.0

In [144]:
recall_score(y_test,y_pred)

1.0